[llm]
api_type = "deepseek"
model = "deepseek-chat"
api_key = "sk-6dbb1f7739da4104a577b365c2ac2f39"
base_url = "https://api.deepseek.com"
max_input_tokens = 65536
max_completion_tokens = 4096
temperature = 0.1

[llm.default]
api_type = "deepseek"
model = "deepseek-chat"
api_key = "sk-6dbb1f7739da4104a577b365c2ac2f39"
base_url = "https://api.deepseek.com"
max_input_tokens = 65536
max_completion_tokens = 4096
temperature = 0.1